# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Form-Processor-Model-DBIC
version:      0.06
version_from: lib/Form/Processor/Model/DBIC.pm
installdirs:  site
requires:
    Carp:                          0
    DBIx::Class:                   0
    Form::Processor:               0.18
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
